version: '3.9'

services:
  web:
    build: .
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - "8002:8000"
    depends_on:
      - db

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5434:5432"

volumes:
  postgres_data: